# This Makefile is generated by the made script:
# https://github.com/alx741/made
#
# Replace FILE with your filename
# Replace MMCU with the target chip model
#
# Dependencies:
# 	avr-gcc
# 	avr-binutils
# 	avrdude


FILE=example
MMCU=atmega32a
AVRDUDE_PART=m32
AVRDUDE_PROGRAMMER=usbasp
F_CPU=1000000


CFLAGS =
CFLAGS += -mmcu=$(MMCU)
CFLAGS += -DF_CPU=$(F_CPU)UL
CFLAGS += -Os
CFLAGS += -g


$(FILE).hex: $(FILE).elf
	avr-objcopy -j .text -j .data -O ihex $< $@

$(FILE).elf: $(FILE).c spi.c
	avr-gcc $(CFLAGS) $? -o $@

clean:
	rm $(FILE).elf $(FILE).hex spi.elf

burn: $(FILE).hex
	sudo avrdude -p $(AVRDUDE_PART) -c $(AVRDUDE_PROGRAMMER) -U flash:w:$(FILE).hex

test: burn
	tmux new-window -c ~ -n "picocom" sudo picocom -c /dev/ttyUSB0 -b 4800
